using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;

namespace Gameplay.CodeGen;

/// <summary>扫描 [Replicated] 组件，生成 serializer + diff + RegisterAll 三件套。</summary>
[Generator]
public class ReplicationGenerator : IIncrementalGenerator
{
    private const string ReplicatedShortName = "Replicated";
    private const string ReplicatedFullName = "ReplicatedAttribute";
    private const string RegistryFullName = "Gameplay.Replication.ReplicationRegistry";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var compilation = context.CompilationProvider;
        var components = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is TypeDeclarationSyntax tds && HasReplicated(tds),
            transform: static (ctx, _) => TransformComponent(ctx)
        ).Where(static info => info.StructName != null);

        var combined = components.Collect().Combine(compilation);
        context.RegisterSourceOutput(combined, static (spc, pair) => GenerateCode(spc, pair.Left, pair.Right));
    }

    private static bool HasReplicated(TypeDeclarationSyntax typeDecl)
    {
        foreach (var list in typeDecl.AttributeLists)
            foreach (var attr in list.Attributes)
            {
                var name = attr.Name.ToString();
                if (name == ReplicatedShortName || name == ReplicatedFullName)
                    return true;
            }
        return false;
    }

    private static ComponentInfo TransformComponent(GeneratorSyntaxContext ctx)
    {
        var typeDecl = (TypeDeclarationSyntax)ctx.Node;
        var typeSymbol = ctx.SemanticModel.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol;
        if (typeSymbol == null || typeSymbol.TypeKind != TypeKind.Structure)
            return default;

        var fields = new List<FieldInfo>();
        foreach (var member in typeSymbol.GetMembers())
        {
            if (member is not IFieldSymbol field || field.IsStatic || field.IsImplicitlyDeclared)
                continue;
            var kind = Classify(field.Type);
            if (kind == FieldKind.Unsupported)
                return default;   // 不支持的字段类型 → 跳过该组件（诊断由编译期缺失序列化器暴露）
            fields.Add(new FieldInfo { Name = field.Name, Kind = kind, TypeName = field.Type.Name });
        }

        return new ComponentInfo
        {
            StructNamespace = typeSymbol.ContainingNamespace?.ToDisplayString() ?? string.Empty,
            StructName = typeSymbol.Name,
            Fields = fields,
        };
    }

    private static FieldKind Classify(ITypeSymbol type)
    {
        switch (type.SpecialType)
        {
            case SpecialType.System_Int32:
            case SpecialType.System_Single:
            case SpecialType.System_Boolean:
                return FieldKind.Primitive;
        }
        if (type.TypeKind == TypeKind.Enum)
            return FieldKind.Enum;
        if (type.Name == "Vector3" && type.ContainingNamespace?.ToDisplayString() == "Gameplay.Core")
            return FieldKind.Vector3;
        if (type.Name == "Quaternion" && type.ContainingNamespace?.ToDisplayString() == "Gameplay.Core")
            return FieldKind.Quaternion;
        return FieldKind.Unsupported;
    }

    private static void GenerateCode(SourceProductionContext spc, ImmutableArray<ComponentInfo> components, Compilation compilation)
    {
        if (components.IsDefaultOrEmpty) return;
        var sorted = components.Sort(static (a, b) => string.CompareOrdinal(a.StructName, b.StructName));

        // 每个组件生成 XxxSerializer + XxxReplication（任何程序集，只要组件标了 [Replicated]）
        foreach (var c in sorted)
        {
            spc.AddSource($"{c.StructNamespace}.{c.StructName}.Replication.g.cs", GeneratePerComponent(c));
        }

        // RegisterAll 只在定义 ReplicationRegistry 的程序集生成
        if (HasReplicationRegistry(compilation))
            spc.AddSource("ReplicatedComponentRegistration.g.cs", GenerateRegisterAll(sorted));
    }

    private static bool HasReplicationRegistry(Compilation compilation)
        => compilation.GetTypeByMetadataName(RegistryFullName) != null
           && SymbolEqualityComparer.Default.Equals(
               compilation.GetTypeByMetadataName(RegistryFullName)!.ContainingAssembly,
               compilation.Assembly);

    private static string GeneratePerComponent(ComponentInfo c)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using Friflo.Engine.ECS;");
        sb.AppendLine("using Gameplay.Core;");
        sb.AppendLine("using Gameplay.Replication;");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(c.StructNamespace))
            sb.AppendLine($"namespace {c.StructNamespace};");
        sb.AppendLine();

        // Serializer
        sb.AppendLine($"public sealed class {c.StructName}Serializer : IComponentSerializer<{c.StructName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public void Write(in {c.StructName} c, ref ByteWriter w)");
        sb.AppendLine("    {");
        foreach (var f in c.Fields)
            sb.AppendLine($"        {WriteExpr(f, "c")}");
        sb.AppendLine("    }");
        sb.AppendLine($"    public void Read(ref {c.StructName} c, ref ByteReader r)");
        sb.AppendLine("    {");
        foreach (var f in c.Fields)
            sb.AppendLine($"        {ReadExpr(f, "c")}");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Diff
        sb.AppendLine($"public readonly struct {c.StructName}Replication : IReplicationDiff<{c.StructName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public bool Equals(in {c.StructName} a, in {c.StructName} b)");
        sb.AppendLine($"        => {EqualsExpr(c)};");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateRegisterAll(ImmutableArray<ComponentInfo> sorted)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using Gameplay.Core;");
        sb.AppendLine("using Gameplay.Replication;");
        sb.AppendLine();
        sb.AppendLine("namespace Gameplay.Replication;");
        sb.AppendLine();
        sb.AppendLine("public static class ReplicatedComponentRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static void RegisterAll()");
        sb.AppendLine("    {");
        foreach (var c in sorted)
        {
            sb.AppendLine($"        SerializerRegistry.Register(new {c.StructName}Serializer());");
            sb.AppendLine($"        ReplicationRegistry.Register<{c.StructName}>(new {c.StructName}Replication());");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string WriteExpr(FieldInfo f, string obj)
        => f.Kind switch
        {
            FieldKind.Primitive => $"w.Write({obj}.{f.Name});",
            FieldKind.Enum => $"w.Write((int){obj}.{f.Name});",
            FieldKind.Vector3 => $"w.Write(in {obj}.{f.Name});",
            FieldKind.Quaternion => $"w.Write(in {obj}.{f.Name});",
            _ => string.Empty,
        };

    private static string ReadExpr(FieldInfo f, string obj)
        => f.Kind switch
        {
            FieldKind.Primitive => $"{obj}.{f.Name} = r.Read{PrimitiveRead(f)}();",
            FieldKind.Enum => $"{obj}.{f.Name} = ({f.TypeName})r.ReadInt();",
            FieldKind.Vector3 => $"{obj}.{f.Name} = r.ReadVector3();",
            FieldKind.Quaternion => $"{obj}.{f.Name} = r.ReadQuaternion();",
            _ => string.Empty,
        };

    private static string PrimitiveRead(FieldInfo f)
        => f.TypeName switch
        {
            "Int32" => "Int",
            "Single" => "Float",
            "Boolean" => "Bool",
            _ => "Int",
        };

    private static string EqualsExpr(ComponentInfo c)
    {
        if (c.Fields.Count == 0) return "true";
        var parts = new List<string>();
        foreach (var f in c.Fields)
        {
            // Vector3/Quaternion 未定义 operator==（实现 IEquatable<T>），用 .Equals() 比较
            if (f.Kind == FieldKind.Vector3 || f.Kind == FieldKind.Quaternion)
                parts.Add($"a.{f.Name}.Equals(b.{f.Name})");
            else
                parts.Add($"a.{f.Name} == b.{f.Name}");
        }
        return string.Join(" && ", parts);
    }

    private enum FieldKind { Primitive, Enum, Vector3, Quaternion, Unsupported }

    private struct FieldInfo { public string Name; public FieldKind Kind; public string TypeName; }

    private struct ComponentInfo
    {
        public string StructNamespace;
        public string StructName;
        public List<FieldInfo> Fields;
    }
}
